# Generated by Django 6.0.2 on 2026-02-28 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choferes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('cheque', 'Cheque'), ('transferencia', 'Transferencia')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='choferes.chofer')),
                ('conduce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='choferes.conduce')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago a chofer',
                'verbose_name_plural': 'Pagos a choferes',
                'ordering': ('-fecha', '-id'),
            },
        ),
    ]
