# Generated by Django 6.0.2 on 2026-03-27 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0004_chofer_carta_buena_conducta_chofer_rntt'),
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='descuento_avances',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='pago',
            name='liquido_avances',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='AvanceChofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('liquidado', 'Liquidado')], default='pendiente', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='choferes.chofer')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_chofer_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avance a chofer',
                'verbose_name_plural': 'Avances a choferes',
                'ordering': ('-fecha', '-id'),
            },
        ),
    ]
