# Generated by Django 5.2.8 on 2026-04-02 14:31

from django.db import migrations, models
from django.db.models import F


def _backfill_combustible_data(apps, schema_editor):
    AvanceChofer = apps.get_model("pagos", "AvanceChofer")

    AvanceChofer.objects.filter(monto__gt=0, galones=0).update(galones=1)
    AvanceChofer.objects.filter(monto__gt=0, precio_por_galon=0).update(
        precio_por_galon=F("monto")
    )
    AvanceChofer.objects.filter(saldo_pendiente__isnull=True).update(
        saldo_pendiente=F("monto")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_descuento_avances_pago_liquido_avances_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avancechofer',
            options={'ordering': ('-fecha', '-id'), 'verbose_name': 'Suministro de combustible a chofer', 'verbose_name_plural': 'Suministros de combustible a choferes'},
        ),
        migrations.AddField(
            model_name='avancechofer',
            name='galones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='avancechofer',
            name='precio_por_galon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(_backfill_combustible_data, migrations.RunPython.noop),
    ]
