# Generated by Django 5.2.8 on 2026-04-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_avancechofer_options_avancechofer_galones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='numero_cheque',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_recibo_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('transferencia', 'Transferencia')], max_length=20),
        ),
    ]
