# Generated by Django 5.2.8 on 2026-04-02 15:57

from django.db import migrations, models


def _migrar_conduce_a_conduces(apps, schema_editor):
    Pago = apps.get_model("pagos", "Pago")
    for pago in Pago.objects.exclude(conduce__isnull=True).iterator():
        pago.conduces.add(pago.conduce_id)


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0004_chofer_carta_buena_conducta_chofer_rntt'),
        ('pagos', '0004_pago_numero_cheque_pago_numero_recibo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='conduces',
            field=models.ManyToManyField(blank=True, related_name='pagos_multiples', to='choferes.conduce'),
        ),
        migrations.RunPython(_migrar_conduce_a_conduces, migrations.RunPython.noop),
    ]
