# Generated by Django 6.0.2 on 2026-03-26 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_seed_tipos_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='PagoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('transferencia', 'Transferencia')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='recursos_humanos.empleado')),
            ],
            options={
                'verbose_name': 'Pago de empleado',
                'verbose_name_plural': 'Pagos de empleados',
                'ordering': ('-fecha', '-id'),
            },
        ),
    ]
