# Generated by Django 6.0.2 on 2026-03-27

from django.db import migrations, models


def poblar_fecha_fin_desde_inicio(apps, schema_editor):
    Capacitacion = apps.get_model("recursos_humanos", "Capacitacion")
    Capacitacion.objects.filter(fecha_fin__isnull=True).update(fecha_fin=models.F("fecha_inicio"))


class Migration(migrations.Migration):
    dependencies = [
        ("recursos_humanos", "0003_empleado_apellidos_pagoempleado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="capacitacion",
            old_name="fecha",
            new_name="fecha_inicio",
        ),
        migrations.AddField(
            model_name="capacitacion",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(
            poblar_fecha_fin_desde_inicio, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="capacitacion",
            name="fecha_fin",
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name="capacitacion",
            name="horas",
        ),
        migrations.AlterModelOptions(
            name="capacitacion",
            options={
                "ordering": ("-fecha_inicio",),
                "verbose_name": "Capacitaci\u00f3n",
                "verbose_name_plural": "Capacitaciones",
            },
        ),
    ]
