# Generated by Django 5.2.8 on 2026-04-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_capacitacion_fechas'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de la capacitacion, si aplica.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='pagada_sin_disfrute',
            field=models.BooleanField(default=False, help_text='Indica si las vacaciones fueron pagadas sin disfrute de dias.', verbose_name='Pagada sin disfrute'),
        ),
    ]
