# Generated by Django 6.0.2 on 2026-04-02 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_empleado_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('con_comprobante', models.BooleanField(default=False)),
                ('numero_comprobante', models.CharField(blank=True, max_length=80)),
                ('proveedor', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('itbis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('propinas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de gasto',
                'verbose_name_plural': 'Registros de gastos',
                'ordering': ('-fecha', '-id'),
            },
        ),
    ]
