# Generated by Django 6.0.2 on 2026-04-09 12:25

from django.db import migrations, models


def completar_quincena_desde_fecha(apps, schema_editor):
    PagoEmpleado = apps.get_model("recursos_humanos", "PagoEmpleado")
    PagoEmpleado.objects.filter(fecha__day__lte=15).update(quincena="primera")
    PagoEmpleado.objects.filter(fecha__day__gt=15).update(quincena="segunda")


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0007_registrogasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoempleado',
            name='quincena',
            field=models.CharField(choices=[('primera', 'Primera quincena'), ('segunda', 'Segunda quincena')], default='primera', max_length=10),
        ),
        migrations.RunPython(
            completar_quincena_desde_fecha,
            migrations.RunPython.noop,
        ),
    ]
