# Generated by Django 6.0.2 on 2026-02-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos_humanos', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('licencia', models.CharField(max_length=50)),
                ('categoria_licencia', models.CharField(blank=True, max_length=50)),
                ('vencimiento_licencia', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_chofer', to='recursos_humanos.empleado')),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Conduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField()),
                ('origen', models.CharField(blank=True, max_length=150)),
                ('destino', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('monto_generado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('liquidado', 'Liquidado'), ('pagado', 'Pagado')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduces', to='choferes.chofer')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduces', to='tracking.vehiculo')),
            ],
            options={
                'verbose_name': 'Conduce',
                'verbose_name_plural': 'Conduces',
                'ordering': ('-fecha', '-id'),
            },
        ),
    ]
