# Generated by Django 6.0.2 on 2026-03-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chofer',
            options={'ordering': ('nombre',), 'verbose_name': 'Chofer subcontratista', 'verbose_name_plural': 'Choferes subcontratistas'},
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='empleado',
        ),
    ]
