# Generated by Django 6.0.2 on 2026-03-03 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0002_alter_chofer_options_remove_chofer_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='banco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chofer',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AddField(
            model_name='chofer',
            name='honorario_referencial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='chofer',
            name='metodo_pago_preferido',
            field=models.CharField(blank=True, choices=[('cheque', 'Cheque'), ('transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.AddField(
            model_name='chofer',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chofer',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
