# Generated by Django 6.0.2 on 2026-03-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0003_chofer_banco_chofer_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='carta_buena_conducta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chofer',
            name='rntt',
            field=models.BooleanField(default=False),
        ),
    ]
