# Generated by Django 5.2.8 on 2026-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0004_chofer_carta_buena_conducta_chofer_rntt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='seguro_ley',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chofer',
            name='vencimiento_carnet_rntt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chofer',
            name='vencimiento_seguro_ley',
            field=models.DateField(blank=True, null=True),
        ),
    ]
