# Generated by Django 5.2.8 on 2026-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0005_chofer_seguro_ley_chofer_vencimiento_carnet_rntt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='suspension_automatica_vencimiento',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
