# Generated by Django 5.2.8 on 2026-04-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0006_chofer_suspension_automatica_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='suspension_automatica_vencimiento',
        ),
    ]
