# Generated by Django 6.0.2 on 2026-02-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('operativo', 'Operativo'), ('financiero', 'Financiero'), ('rrhh', 'RRHH'), ('flota', 'Flota'), ('otro', 'Otro')], default='operativo', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ('-fecha', '-id'),
            },
        ),
    ]
