# Generated by Django 6.0.2 on 2026-02-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('tipo', models.CharField(max_length=80)),
                ('capacidad', models.CharField(blank=True, max_length=60)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilado', 'Alquilado'), ('mantenimiento', 'Mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='disponible', max_length=20)),
                ('ubicacion_actual', models.CharField(blank=True, max_length=200)),
                ('cliente_actual', models.CharField(blank=True, max_length=150)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_retorno_estimada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=30)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=60)),
                ('capacidad', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilado', 'Alquilado'), ('mantenimiento', 'Mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='disponible', max_length=20)),
                ('ultima_ubicacion', models.CharField(blank=True, max_length=200)),
                ('cliente_actual', models.CharField(blank=True, max_length=150)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_retorno_estimada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ('placa',),
            },
        ),
    ]
