# Generated by Django 6.0.2 on 2026-03-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='dueno_documento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='dueno_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='dueno_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='es_propiedad_empresa',
            field=models.BooleanField(default=True),
        ),
    ]
