# Generated by Django 6.0.2 on 2026-03-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_vehiculo_dueno_documento_vehiculo_dueno_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
