# Generated by Django 6.0.2 on 2026-03-28 02:00

from django.db import migrations, models


def normalizar_estado_contenedor(apps, schema_editor):
    Contenedor = apps.get_model("tracking", "Contenedor")
    Contenedor.objects.filter(estado__in=["mantenimiento", "fuera_servicio"]).update(
        estado="disponible"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_vehiculo_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(
            normalizar_estado_contenedor,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='cliente_actual',
            field=models.CharField(blank=True, max_length=150, verbose_name='A quien se le alquilo'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='codigo',
            field=models.CharField(max_length=40, unique=True, verbose_name='Ficha del contenedor'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('alquilado', 'Alquilado')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_retorno_estimada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='tipo',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
