# Generated by Django 6.0.2 on 2026-04-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_contenedor_color_alter_contenedor_cliente_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='costo_alquiler',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo del alquiler'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='efectivo', max_length=20, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='local_o_importado',
            field=models.CharField(choices=[('local', 'Local'), ('importado', 'Importado')], default='local', max_length=15, verbose_name='Local o importado'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='numero_referencia_pago',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero de referencia de pago'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='referido_por',
            field=models.CharField(blank=True, max_length=150, verbose_name='Referido por'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='servicio_a',
            field=models.CharField(blank=True, max_length=150, verbose_name='A quien se le da el servicio'),
        ),
    ]
