# Generated by Django 6.0.2 on 2026-04-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_contenedor_costo_alquiler_contenedor_forma_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='tamano_pies',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamano (pies)'),
        ),
    ]
