# Generated by Django 6.0.2 on 2026-04-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0007_contenedor_tamano_pies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chasis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=40, unique=True, verbose_name="Ficha del chasis")),
                ("tamano_pies", models.PositiveIntegerField(blank=True, null=True, verbose_name="Tamano (pies)")),
                ("estado", models.CharField(choices=[("disponible", "Disponible"), ("alquilado", "Alquilado")], default="disponible", max_length=20)),
                ("ubicacion_actual", models.CharField(blank=True, max_length=200)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Chasis",
                "verbose_name_plural": "Chasis",
                "ordering": ("codigo",),
            },
        ),
        migrations.CreateModel(
            name="AlquilerContenedor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("con_chasis", models.BooleanField(default=False, verbose_name="Con chasis")),
                ("cliente", models.CharField(max_length=150, verbose_name="A quien se le da el servicio")),
                ("referido_por", models.CharField(blank=True, max_length=150, verbose_name="Referido por")),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(blank=True, null=True, verbose_name="Fecha de fin")),
                ("costo_alquiler", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Costo del alquiler")),
                ("forma_pago", models.CharField(choices=[("efectivo", "Efectivo"), ("transferencia", "Transferencia"), ("cheque", "Cheque")], default="efectivo", max_length=20, verbose_name="Forma de pago")),
                ("numero_referencia_pago", models.CharField(blank=True, max_length=50, verbose_name="Numero de referencia de pago")),
                ("estado", models.CharField(choices=[("activo", "Activo"), ("cerrado", "Cerrado")], default="activo", max_length=20)),
                ("observaciones", models.TextField(blank=True)),
                ("chasis", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="alquileres", to="tracking.chasis", verbose_name="Chasis")),
                ("contenedor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="alquileres", to="tracking.contenedor", verbose_name="Contenedor")),
            ],
            options={
                "verbose_name": "Alquiler de contenedor",
                "verbose_name_plural": "Alquileres de contenedores",
                "ordering": ("-fecha_inicio", "-id"),
            },
        ),
    ]
