# Generated by Django 6.0.2 on 2026-04-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_chasis_alquiler_contenedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquilercontenedor',
            name='numero_contacto_referencia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero de contacto de referencia'),
        ),
    ]
