# Generated by Django 6.0.2 on 2026-04-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alquilercontenedor_numero_contacto_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquilercontenedor',
            name='numero_contrato_compromiso',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero de contrato de compromiso'),
        ),
    ]
