# Generated by Django 6.0.2 on 2026-04-21 20:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_alquilercontenedor_numero_contrato_compromiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibo', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de recibo')),
                ('observaciones', models.TextField(blank=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='tracking.alquilercontenedor', verbose_name='Alquiler de contenedor')),
            ],
            options={
                'verbose_name': 'Recibo de contenedor',
                'verbose_name_plural': 'Recibos de contenedores',
                'ordering': ('-fecha_recibo', '-id'),
            },
        ),
    ]
