# Generated by Django 5.2.8 on 2026-04-02 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.localdate, editable=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa proveedora',
                'verbose_name_plural': 'Empresas proveedoras',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='RegistroProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('placa', models.CharField(max_length=20)),
                ('ruta', models.CharField(help_text='Salida / destino', max_length=200)),
                ('numero_transporte', models.CharField(max_length=50, verbose_name='No. de transporte')),
                ('destino', models.CharField(max_length=120)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Registro operativo de proveedor',
                'verbose_name_plural': 'Registros operativos de proveedores',
                'ordering': ('-fecha', '-id'),
            },
        ),
    ]
